[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-cos-akyk  github-pr-3074c-microk8s  microk8s/localhost  3.6.8    unsupported  13:55:08Z

App             Version  Status  Scale  Charm           Channel   Rev  Address         Exposed  Message
loki-k8s        2.9.6    active      1  loki-k8s        1/stable  199  10.152.183.248  no       
prometheus-k8s  2.52.0   active      1  prometheus-k8s  1/stable  247  10.152.183.56   no       
vault-k8s                active      3  vault-k8s                   0  10.152.183.151  no       

Unit               Workload  Agent  Address      Ports  Message
loki-k8s/0*        active    idle   10.1.63.223         
prometheus-k8s/0*  active    idle   10.1.63.222         
vault-k8s/0*       active    idle   10.1.63.208         
vault-k8s/1        active    idle   10.1.63.216         
vault-k8s/2        active    idle   10.1.63.217         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-vault-k8s-2: 13:51:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.63.217:55396->10.152.183.233:17070: write: connection reset by peer
unit-vault-k8s-1: 13:51:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-9e93f597-7e61-41f5-8ce7-11da844c1e48: 13:51:58 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 13:51:58 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-cos-akyk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02e8cdc6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 13:52:00 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1049 Resetting model test-cos-akyk...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications prometheus-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications loki-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1054 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...