[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-cos-i1hl  github-pr-4ccf7-microk8s  microk8s/localhost  3.6.10   unsupported  17:57:51Z

App             Version  Status  Scale  Charm           Channel   Rev  Address         Exposed  Message
loki-k8s        2.9.6    active      1  loki-k8s        1/stable  199  10.152.183.85   no       
prometheus-k8s  2.52.0   active      1  prometheus-k8s  1/stable  247  10.152.183.172  no       
vault-k8s                active      3  vault-k8s                   0  10.152.183.199  no       

Unit               Workload  Agent  Address     Ports  Message
loki-k8s/0*        active    idle   10.1.72.95         
prometheus-k8s/0*  active    idle   10.1.72.94         
vault-k8s/0*       active    idle   10.1.72.80         
vault-k8s/1        active    idle   10.1.72.91         
vault-k8s/2        active    idle   10.1.72.88         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 17:54:41 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 17:54:41 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.72.91:41968->10.152.183.151:17070: write: connection reset by peer: write tcp 10.1.72.91:41968->10.152.183.151:17070: write: connection reset by peer
unit-vault-k8s-0: 17:54:41 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-b42b35e2-ac16-4334-880d-dff44e148135: 17:54:42 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 17:54:42 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-cos-i1hl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb72d03f0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-cos-i1hl...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications prometheus-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications loki-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...